### PR TITLE
Fixes PolyHook2Alloca not being inlined

### LINKED ISSUE #149: PLH::findPattern fails due to issue with _alloca
On Windows, using C++ 17 compiled for x86_64 with MSVC 1932, I'm getting a weird issue where `PLH::findPattern` will actually look the character 'x' (0x78) in memory instead of whichever bytes I provided on the signature. 

Upon further inspection, I managed to pin down the issue on the allocations of `patt_base` and `msk_base`. The issue is that `PolyHook2Alloca` is returning the same allocated address for both variables.

debbuger

### PR DESCRIPTION
**Pull request by itisluiz**
PolyHook2Alloca allocates memory dynamically on the stack but it wasn't being inline, causing the memory to be deallocated after it returned.

resolve #149 
Tested only on Windows MSVC.

### CODE REVIEW

File: polyhook2/PolyHookOs.hpp [hunk 1]
```diff
@@ -70,6 +70,15 @@
 #include <inttypes.h>
 
 void PolyHook2DebugBreak();
-void* PolyHook2Alloca(size_t size);
+
+// Methods using stack allocation need to be inlined
+__forceinline void* PolyHook2Alloca(size_t size)
```
Comment (stevemk14ebr) [inline polyhook2/PolyHookOs.hpp:75]: Can you add a new macro definition called PLH_INLINE and have it use either forceinline on msvc or otherwise __attribute__((always_inline)) for gcc and clang. That's probably enough support for now

**Review by stevemk14ebr — CHANGES_REQUESTED** [review]

**Review by stevemk14ebr — APPROVED** [review]
Thanks!
